### ISSUE TITLE
.mobile_only elements are not shown on mobile

### ISSUE THREAD

**Issue by denis-chmel** [Snowfire/Beautymail#32] opened 2016-04-06 11:45 UTC
Hi guys,

Why is there anything called CssInlinerPlugin? Seems it removes completely all tags that has class="mobile_only" from HTML, right before sending email. It probably strips everything else that have "display: none" (which is not under @media level).

After that this rules is never triggered:
https://github.com/Snowfire/Beautymail/blob/master/src/styles/css/ark.css#L63-L66
https://github.com/Snowfire/Beautymail/blob/master/src/styles/css/sunny.css#L63-L66
As there are just no any elements left to apply it to.

I've started using this component yesterday and spend 2 happy hours investigating this issue, and I now have a serious question. Does it work for you really?

**Comment by emilsundberg** [comment] 2016-04-06 12:17
Thanks for you contribution @denis-chmel! 

I just confirmed that this isn't working for me on the current version. Something must have been changed since it has worked before. 

I'll have a deeper look soon, then I'll merge your PR and tag a new version.

**Comment by denis-chmel** [comment] 2016-04-06 13:04
Thank you, Emil.

**Comment by ramsin102** [comment] 2016-04-18 21:57
Any idea when this will be fixed? I spent a couple hours debugging my code today until I came across this posting and realized it wasn't anything that I had done that had broken the emails on mobile.

**Comment by emilsundberg** [comment] 2016-04-19 06:47
Sorry for the delay and thanks for the reminder @ramsin102 :)

The PR is merged and I have tagged a new release 1.0.10

**Comment by ramsin102** [comment] 2016-04-19 20:53
Thanks @emilsundberg it's working like a charm now! :)

**Closed** 2016-04-20 08:06 UTC
